### PR TITLE
Close InputStream after reading it

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by ALRubinger** [comment]
Rejecting. :)  We don't close InputStreams that we're not the authoritative owner of; this was supplied to us as an argument and should be managed by the creator.

**Comment by gastaldi** [comment]
Actually the close should happen in the loadExtensionMapping method. A try-with-resources would do

**Comment by aslakknutsen** [comment]
Agree with @gastaldi, this is our stream :)

We create it here; https://github.com/gastaldi/shrinkwrap/blob/54bf0aaa9643043af6b36c1172dd18dff9f607aa/impl-base/src/main/java/org/jboss/shrinkwrap/impl/base/ServiceExtensionLoader.java#L265 

All within private scope as far as I can tell.

**Comment by gastaldi** [comment]
Re-forked my repo. The link above should be https://github.com/shrinkwrap/shrinkwrap/blob/54bf0aaa9643043af6b36c1172dd18dff9f607aa/impl-base/src/main/java/org/jboss/shrinkwrap/impl/base/ServiceExtensionLoader.java#L265

**Comment by gastaldi** [comment]
Created new PR at https://github.com/shrinkwrap/shrinkwrap/pull/93

**Pull request closed without merging**
