### PR TITLE
[SHRINKWRAP-504] adds ZipStoredExporter

### PR DESCRIPTION
**Pull request by lordofthejars**
https://issues.jboss.org/browse/SHRINKWRAP-504

### CODE REVIEW

**Comment by ALRubinger** [comment]
@lordofthejars Compilation failure on this one:

```
/home/alr/business/jboss/git/shrinkwrap/shrinkwrap/impl-base/src/main/java/org/jboss/shrinkwrap/impl/base/exporter/zip/ZipOnDemandInputStream.java:[99,20] error: try-with-resources is not supported in -source 1.5
```

ShrinkWrap is compiled with JDK1.6 with runtime dependencies to 1.5; env var `JAVA5_HOME` should point to a JDK5 installation. :)

**Comment by ALRubinger** [comment]
Instructions here (really need to be ported to a README in this repo as things have aged):

https://developer.jboss.org/wiki/ShrinkWrapDevelopmentAndContribution

**Comment by lordofthejars** [comment]
Right, I need to check. The problem was that I copied pasted from my
project that was with java 7

Instructions here (really need to be ported to a README in this repo as
things have aged):

https://developer.jboss.org/wiki/ShrinkWrapDevelopmentAndContribution

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/shrinkwrap/shrinkwrap/pull/98#issuecomment-221339498>

**Comment by ALRubinger** [comment]
fe8805904e25d99c34dd2576c15f7e4f01160c99

**Pull request closed without merging**
