### PR TITLE
[SHRINKWRAP-539] Cleaning up the pom

### PR DESCRIPTION
**Pull request by khermano**
Issue: https://issues.redhat.com/browse/SHRINKWRAP-539

### CODE REVIEW

**Comment by petrberan** [comment]
Looks good @khermano 

Two minor things, can we have the dependency versions sorted alphabetically? IDEA already has a shortcut for that: 2x Shift -> Sort Lines
Just a matter of taste, but in case of artifactId starting with the same word that groupId is ending, I tend to remove the extra word: `<version.junit.junit>` -> `<version.junit>` . What's your opinion on that?

**Comment by khermano** [comment]
Sounds good to me. I am on it. 
Thank you for the review.

**Comment by petrberan** [comment]
Well if we went the way of "shortening" the duplicate artifactIDs for jUnit, we might as well go with

`version.org.jboss.apiviz.apiviz` -> `version.org.jboss.apiviz`
and
`version.org.jacoco.jacoco-maven-plugin` -> `version.org.jacoco-maven-plugin`

What do you think? @khermano

**Comment by khermano** [comment]
@petrberan   sounds good to me. 
I pushed the changes.

**Review by petrberan — APPROVED** [review]
LGTM, thx @khermano

**Pull request merged**
